### ISSUE TITLE
.merge-branch-heading is not styled

### ISSUE THREAD

**Issue by vovanmix** [vovanmix/github-dark-theme#1]
```css
.merge-branch-heading {
    margin: 0;
    line-height: 1;
    color: #24292e;
}
```
