### ISSUE TITLE
Tweaks

### ISSUE THREAD

**Issue by vovanmix** [vovanmix/github-dark-theme#2]
- Make `.markdown-body code, .markdown-body tt ` the same bg as `.markdown-body .highlight pre, .markdown-body pre`

- make `.release-label` bg as in tags

-  make this of the opposite color:
```
.pl-mb {
    font-weight: bold;
    color: #333;
}
```
- fix this to have some bg color brighter than `#2c313a;`:
```
.select-menu-item.navigation-focus, .select-menu-item.navigation-focus.selected, .select-menu-item.navigation-focus.select-menu-action, .select-menu-item.navigation-focus .description-inline
```

- `.branch-infobar` is too bright

- make border-right dark:
```css
.file-diff-split .blob-code + .blob-num {
    border-right: 1px solid rgb(24, 26, 31) !important;
}
```

- this has too bright bg:
```
.email-format .email-hidden-toggle a {
  background: #dfe2e5;
}
```
