### ISSUE TITLE
Batch #3

### ISSUE THREAD

**Issue by vovanmix** [vovanmix/github-dark-theme#3]
1. Add firacode / menlo to `tt, code`

2. make dropdown hovered state visible:
```
.select-menu-item.navigation-focus, .select-menu-item.navigation-focus.selected, .select-menu-item.navigation-focus.select-menu-action, .select-menu-item.navigation-focus .description-inline
```

3. Make the commit desc text lighter (#aaa will be fine):
```
.commit-desc pre
```

5. Invert color:
```css
.bg-gray-light {
    background-color: #fafbfc !important;
}
```

6. make this white:
```css
.tag-info h3 a .tag-name {
    color: #000;
}
```
7. Invert BG of this header:
```css
.Box-header {
    padding: 16px;
    margin: -1px -1px 0 -1px;
    background-color: #f6f8fa;
    border-color: #d1d5da;
    border-style: solid;
    border-width: 1px;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
}
```
8. invert bg of this panel:
```css
.conversation-list-heading .inner {
    position: relative;
    top: -10px;
    display: inline-block;
    padding: 0 5px;
    background: #fff;
}
```
