### ISSUE TITLE
codecov hits/misses bg in file view

### ISSUE THREAD

**Issue by vovanmix** [vovanmix/github-dark-theme#4]
1?. Make codecov hits/misses bg darker (when opening the file):
```css
td.blob-code.codecov.codecov-on.codecov-hit {
  background-color: #eaffea;
}
td.blob-code.codecov.codecov-on.codecov-missed {
  background-color: #ffecec;
}
```
