### ISSUE TITLE
Batch #4

### ISSUE THREAD

**Issue by vovanmix** [vovanmix/github-dark-theme#5]
1. make `.branch-name` color whitish
```css
.branch-name {
    color: rgba(27,31,35,0.6);
}
```

2.  make this text color like link color:
```css
.access-token .token-description
```

3. codemirror broke:
```
.cm-s-github-light .CodeMirror-lines
```

4. .branch-name on a label in newsfeed is too dark

5. `.review-summary-form-wrapper` (writing review panel) has a white BG

6. md text in diff is too dark:
```
.pl-mi {
    font-style: italic;
    color: #24292e;
}
```
